# This file lists commands that conflict with other bots on the network.
# TARS will not respond to these commands unless that bot is not present.

[[bot]]
name = "Secretary_Helen"
last_updated = "2021-03-23"
prefix = "."
# Helen's documentation is missing some commands, so the source code is scraped
# directly:
# https://github.com/DoctaMag/HelenBot/blob/master/src/com/helen/commands/Command.java
# https://rossjrw.com/series-replace/?f=%5B%5CS%5Cs%5D%2A%3F%28%40IRCCommand.%2A%29%24&f=%40IRCCommand%5C%28%28.%2B%3F%29%5C%29%5Cn%5B%5CS%5Cs%5D%2A%3F&f=%E0%B0%B5%5B%5E%E0%B0%B5%5D%2A%24&f=command%20%3D%20%28%22%5B%5E%3D%5D%2B%3F%22%7C%7B%22%5B%5E%3D%5D%2B%3F%22%7D%29.%2A%28%5Cn%7C%24%29&f=%28%28%5Cn%7C%5E%29%7B%29%7C%28%7D%28%5Cn%7C%24%29%29&f=%2C%5Cs%2A&f=%28%28%3F%3C%3D%5Cn%29%7C%5E%29%22%5C.%3F&f=%5Cn&r=%241%5Cn&r=%241%E0%B0%B5%5Cn&r=&r=%241%5Cn&r=%242%244&r=%5Cn&r=%20%20%22&r=%2C%5Cn
commands = [
  "HelenBot",
  "modeToggle",
  "addCommand",
  "deleteCommand",
  "getcommands",
  "listcommands",
  "commands",
  "ch",
  "choose",
  "mode",
  "msg",
  "addNick",
  "deleteNick",
  "deleteAllNicks",
  "nicks",
  "deleteNicksAdmin",
  "roll",
  "hugme",
  "rem",
  "meh",
  "deleteRem",
  "hugHelen",
  "helenhug",
  "hugsplox",
  "g",
  "google",
  "lmgtfy",
  "gis",
  "w",
  "wiki",
  "wikipedia",
  "y",
  "yt",
  "youtube",
  "helen",
  "helenHelp",
  "help",
  "hlt",
  "seen",
  "sm",
  "findBan",
  "addBan",
  "deleteBan",
  "updateBan",
  "confirmAdd",
  "confirmDelete",
  "cancelAdd",
  "cancelDelete",
  "lc",
  "l",
  "unused",
  "unu",
  "au",
  "SCPPAGEREGEX",
  "ur",
  "SCP",
  "s",
  "sea",
  "hs",
  "hsea",
  "pronouns",
  "pronoun",
  "myPronouns",
  "helenconf",
  "setPronouns",
  "clearPronouns",
  "deletePronouns",
  "def",
  "definition",
  "join",
  "leave",
  "o5",
  "tell",
  "masstell",
  "mtell",
  "exit",
  "property",
  "setProperty",
  "updateProperty",
  "deleteProperty",
  "clearCache",
  "clear",
  "shoot",
  "reload",
  "setTimezone",
  "getTimezone",
  "timezone",
  "log",
  "flog",
  "dotCommand",
  "deleteTimezone",
  "unload",
  "q",
  "quote",
  "addQuote",
  "aq",
  "removeQuote",
  "rq",
  "updateBans",
  "user",
  "contest",
  "blackbox",
]
