# This file lists commands that conflict with other bots on the network.
# TARS will not respond to these commands unless that bot is not present.

[[bot]]
name = "Secretary_Helen"
last_updated = "2021-03-23"
prefix = "."
commands = [
  "def",
  "definition",
  "exit",
  "g",
  "google",
  "gis",
  "helen",
  "helenHelp",
  "help",
  "hlt",
  "hugHelen",
  "helenhug",
  "hugsplox",
  "hugme",
  "join",
  "lc",
  "l",
  "leave",
  "au",
  "ch",
  "choose",
  "reload",
  "roll",
  "s",
  "sea",
  "seen",
  "setTimezone",
  "shoot",
  "sm",
  "tell",
  "masstell",
  "timezone",
  "unload",
  "user",
  "unused",
  "unu",
  "ur.w",
  "wiki",
  "wikipedia",
  "y",
  "yt",
  "youtube",
  "HelenBot",
  "clearPronouns",
  "deletePronouns",
  "myPronouns",
  "pronouns",
  "pronoun",
  "setPronouns",
  "addNick",
  "deleteAllNicks",
  "deleteNick",
  "deleteNicksAdmin",
  "mode",
  "modeToggle",
  "o5",
  "clearCache",
  "clear",
  "setProperty",
  "log",
  "flog",
  "addCommand",
  "listcommands",
  "deleteCommand",
]
